name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the Docker image
        run: | 
          docker login --username esorrie --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/esorrie/edscore-app:latest
          docker push ghcr.io/esorrie/edscore-app:latest


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push the Image to Amazon ECR
        id: build-image
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: edscore-app
          IMAGE_TAG: latest
        run: | 
          docker login -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push  $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
